services:
  # Backend API Service
  - type: web
    name: e-folio-backend
    env: node
    plan: starter
    region: oregon
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # Add this manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false  # Add your Netlify URL here

# ============================================
# DEPLOYMENT NOTES
# ============================================
# Frontend: Already deployed on Netlify ✅
# Backend: Deploy to Render using this config
#
# REQUIRED ENVIRONMENT VARIABLES (Add in Render Dashboard):
# 1. MONGODB_URI - Your MongoDB Atlas connection string
# 2. CLIENT_URL - Your Netlify URL (e.g., https://e-folio-pro.netlify.app)
#
# NETLIFY ENVIRONMENT VARIABLES (Update in Netlify Dashboard):
# 1. VITE_API_URL - Your Render backend URL (e.g., https://e-folio-backend.onrender.com)
# 2. VITE_SOCKET_URL - Your Render backend URL (e.g., https://e-folio-backend.onrender.com)
